name: verify
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cowsay:
    runs-on: self-hosted
    container: npalm/cowsay

    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello how are you doing here 1 2 4 "
