name: edl-load-testing
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  willDeployToLowerEnvironments: 'true'
  project_name: edl-load-testing
  
jobs:
 DeploymentSetup:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - name: Deployment Setup
     run: |
        ls -lrt
        find ./src/it/resources/scenarios -type f -exec basename {} \; >> scenario.txt
        scenario=$(cat ./scenario.txt)
        sh "find ./src/it/resources/user_simulations -type f -exec basename {} \; >> user.txt"
        user=$(cat ./user.txt)
        find ./src/it/resources/feeder -type f -exec basename {} \; >> feeds.txt"
        sed  -i '1i notRequiredFeeder' feeds.txt
        feeds=$(cat ./feeds.txt)
   - name: Package
     if: github.event.ref == 'refs/heads/main' && $willDeployToLowerEnvironments == 'true'
     run: |
       zipAndStash('zip', project_name)
       echo "::set-output name=url::$(sh(returnStdout: true, script: 'git config remote.origin.url').trim())"
       echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
       echo "::set-output name=url::'https://github.deere.com/EDL/${project_name}.git
