name: edl-data-catalog-regression
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define env name'     
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - ubuntu-latest
        - ubuntu-20.04
        
      LAKERS:
        description: 'Select true if lakers environment'     
        required: true
        default: 'false'
env:
  SRCCLR_API_TOKEN: ${{secrets.SRCCLR_API_TOKEN}}
  
  
jobs:
   edl-data-catalog-regression:
     name: edl-data-catalog-regression
     runs-on: "${{ github.event.inputs.environment}}"
     steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
    
      - name: Nodejs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '12.13.0'
     
