name: edl-entitlement-key-manager
on:
 schedule:
    - cron:  '01 00 * * *'
  # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
env:
  willDeployToLowerEnvironments: false 
  BRANCH_NAME: 'master'
  CIS_DEVL_AWS_ACCT: ${{secrets.CIS_DEVL_AWS_ACCT}}
  CIS_PROD_AWS_ACCT: ${{secrets.CIS_PROD_AWS_ACCT}}
  CIS_AWS_REGION: ${{secrets.IS_AWS_REGION}}
  project_name: "edl-entitlement-key-manager"
  region: env.CIS_AWS_REGION
  sta
  envNamesAndAccounts: [ [devl,{{env.CIS_DEVL_AWS_ACCT}}],[prod,{{env.CIS_PROD_AWS_ACCT}}] ]
steps:
jobs:
  DeploymentSetup:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Read environment.yml
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: ./environment.yml
    - name: Echo package.json
      run: echo "${{ steps.package.outputs.content }}"
   Veracode SCA:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      if: ${{ {{env.willDeployToLowerEnvironments}} = 'true' }}
      - name: Set env
      run: |
         echo "url=$(echo $url| returnStdout: true, script: 'git config remote.origin.url)"
    - name: Test
      run: echo $url
      run:
         
      def willDeployToProd = BRANCH_NAME == 'master' && (url == "git@github.deere.com:EDL/${project_name}.git" || url == "https://github.deere.com/EDL/${project_name}.git")
      
       
    
   
