name: edl-files-regression
on: 
 workflow_dispatch:
 
env:
  ENVIRONMENT: devl
  ARTIFACTORY_USER: ${{secrets.CIS_ARTIFACTORY_USER}}
  ARTIFACTORY_API_KEY: ${{secrets.CIS_ARTIFACTORY_API_KEY}}
  CIS_DEVL_AUTH_CLIENT_ID: ${{secrets.CIS_DEVL_AUTH_CLIENT_ID}}
  CIS_DEVL_AUTH_CLIENT_SECRET: ${{secrets.CIS_DEVL_AUTH_CLIENT_SECRET}}
  CIS_PROD_AUTH_CLIENT_ID: ${{secrets.CIS_PROD_AUTH_CLIENT_ID}}
  CIS_PROD_AUTH_CLIENT_SECRET: ${{secrets.CIS_PROD_AUTH_CLIENT_SECRET}}
  
jobs:
   edl-files-regression:
     name: edl-files-regression
     runs-on: [ devl ]
     steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Build and Integration Test
        shell: bash
        run: |
           echo "Testing..."
           echo  "${params.ENVIRONMENT}"
          # sh "${tool name: 'sbt-1.1.1', type: 'org.jvnet.hudson.plugins.SbtPluginBuilder$SbtInstallation'}/bin/sbt  -DBuild_Environment=${env.ENVIRONMENT} it:test"
     
      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v2
        with:
           # mail server settings
           server_address: smtp.gmail.com
           server_port: 465
           # user credentials
           username: ${{ secrets.EMAIL_USERNAME }}
           password: ${{ secrets.EMAIL_PASSWORD }}
           # email subject
           subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
           body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
           to: natasha85.chaturvedi@gmail.com
         # from email name
           from: natasha85.chaturvedi@gmail.com
