name: edl-entitlement-key-manager
on:
 schedule:
    - cron:  '01 00 * * *'
  # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
env:
  willDeployToLowerEnvironments: 'false'
  BRANCH_NAME: 'master'
  CIS_DEVL_AWS_ACCT: ${{secrets.CIS_DEVL_AWS_ACCT}}
  CIS_PROD_AWS_ACCT: ${{secrets.CIS_PROD_AWS_ACCT}}
  CIS_AWS_REGION: ${{secrets.IS_AWS_REGION}}
  project_name: "edl-entitlement-key-manager"
  region: CIS_AWS_REGION
jobs:
   DeploymentSetup:
     name: DeploymentSetup
     runs-on: ubuntu-latest
     steps: 
     - uses: actions/checkout@v2
     - name: Read environment.yml
       id: package
       uses: juliangruber/read-file-action@v1
       with:
        path: ./environment.yml
     - name: Echo package.json
       run: echo "${{ steps.package.outputs.content }}"
   Veracodesca:
     name: Veracodesca
     runs-on: ubuntu-latest
     steps: 
     - uses: actions/checkout@v2
     - run: |
          git config remote.origin.url >> url 
          echo $url
          echo "willDeployToProd" 
          echo "BRANCH_NAME == 'master'" 
          echo "(url == "git@github.deere.com:EDL/${(env.project_name}.git" || url == "https://github.deere.com/EDL/${(env.project_name}).git")"
     
       
      
         
      
      
       
    
   
