name: edl-entitlement-key-manager
on:
 schedule:
    - cron:  '01 00 * * *'
  # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
env:
  willDeployToLowerEnvironments: false 
  BRANCH_NAME: 'master'
  CIS_DEVL_AWS_ACCT: ${{secrets.CIS_DEVL_AWS_ACCT}}
  CIS_PROD_AWS_ACCT: ${{secrets.CIS_PROD_AWS_ACCT}}
  CIS_AWS_REGION: ${{secrets.IS_AWS_REGION}}
  project_name: "edl-entitlement-key-manager"
  region: env.CIS_AWS_REGION
jobs:
   DeploymentSetup:
     name: DeploymentSetup
     runs-on: ubuntu-latest
     steps: 
     - uses: actions/checkout@v2
     - name: Read environment.yml
       id: package
       uses: juliangruber/read-file-action@v1
       with:
        path: ./environment.yml
     - name: Echo package.json
       run: echo "${{ steps.package.outputs.content }}"
   Veracodesca:
     name: Veracodesca
     runs-on: ubuntu-latest
     if: ${{env.willDeployToLowerEnvironments}} == 'true'
     steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: |
         echo "url=$(echo $url| returnStdout: true, script: 'git config remote.origin.url)"> >> $url
      - name: Test
        run: echo $url
      
         
      
      
       
    
   
