name: edl-data-catalog-regression
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define env name'     
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - ubuntu-latest
        - ubuntu-20.04
        
      LAKERS:
        description: 'Select true if lakers environment'     
        required: true
        default: 'false'
env:
  SRCCLR_API_TOKEN: ${{secrets.SRCCLR_API_TOKEN}}
  
  
jobs:
   edl-data-catalog-regression:
     name: edl-data-catalog-regression
     runs-on: ${{ github.event.inputs.environment}}
     steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
    
      - name: Nodejs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '12.13.0'
   Build-and-run-devl-regression-tests:
    name: Build-and-run-devl-regression-tests
    runs-on:  ${{ github.event.inputs.environment}}
    if: ${{github.event.inputs.environment == 'ubuntu-latest'}}
    steps:
     - with:
        DEV_CATALOG_READ_SECRET: ${{secrets.DEV_CATALOG_READ_SECRET}}
        DEV_CATALOG_WRITE_SECRET: ${{secrets.DEV_CATALOG_WRITE_SECRET}}
        DEV_CATALOG_ADMIN_SECRET: ${{secrets.DEV_CATALOG_ADMIN_SECRET}}
       env:
        DEV_CATALOG_READ_SECRET: ${{secrets.DEV_CATALOG_READ_SECRET}}
        DEV_CATALOG_ADMIN_SECRET: ${{secrets.DEV_CATALOG_ADMIN_SECRET}}
        DEV_CATALOG_WRITE_SECRET: ${{secrets.DEV_CATALOG_WRITE_SECRET}}
        run: |
            npm i
            echo  ${{github.event.inputs.environment}}
            npm run regression
   
   Build-and-run-prod-regression-tests:
      name: Build-and-run-prod-regression-tests
      runs-on:  ${{ github.event.inputs.environment}}
      if: ${{github.event.inputs.environment == 'ubuntu-20.04'}}
      steps:
       - with:
           PROD_CATALOG_READ_SECRET: ${{secrets.PROD_CATALOG_READ_SECRET}}
           PROD_CATALOG_WRITE_SECRET: ${{secrets.PROD_CATALOG_WRITE_SECRET}}
           PROD_CATALOG_ADMIN_SECRET: ${{secrets.PROD_CATALOG_ADMIN_SECRET}}
         env:
           PROD_CATALOG_READ_SECRET: ${{secrets.PROD_CATALOG_READ_SECRET}}
           PROD_CATALOG_ADMIN_SECRET: ${{secrets.PROD_CATALOG_ADMIN_SECRET}}
           PROD_CATALOG_WRITE_SECRET: ${{secrets.PROD_CATALOG_WRITE_SECRET}}
           run: |
            npm i
            echo  ${{github.event.inputs.environment}}
            npm run regression 
            

     
