

name: ci
on:
  workflow_dispatch:


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
    - run: |
        set -x
        docker -v

        docker run --rm hello-world
